---
- name: Add global keyboard shortcuts
  block:
    - name: Extract NSUserKeyEquivalents from GlobalPreferences
      command: defaults read -globalDomain NSUserKeyEquivalents
      register: nsuserkeyequivalents_current
      ignore_errors: True
      changed_when: False

    - name: 'Add or update global keyboard shortcuts'
      command: defaults write -globalDomain NSUserKeyEquivalents  -dict-add '{{ item.key }}' "{{ item.value }}"
      when: item.key ~ '" = "' ~ item.value not in nsuserkeyequivalents_current.stdout
      loop: "{{ global_shortcuts }}"
