---
dependency:
  name: galaxy

driver:
  name: vagrant

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: macos-novars
    groups:
      - novars
    box: macinbox

  - name: macos-usevars
    groups:
      - usevars
    box: macinbox

provisioner:
  name: ansible
  log: True

verifier:
  name: ansible
  enabled: False
